spring.application.name=rideflow-backend

# 1. Database Connection URL (Dynamic for Railway / Render)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rideflow_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# 2. Redis Connection (Dynamic)
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

# 3. Server Port
server.port=${PORT:8080}

# 4. Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 5. JWT Settings
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=604800000

# 6. Payment Gateway
application.payment.razorpay.key-id=${RAZORPAY_KEY_ID:rzp_test_RideFlowKey123}
application.payment.razorpay.key-secret=${RAZORPAY_KEY_SECRET:RideFlowSecret456}
application.payment.commission-rate=0.20